Proj 1 vector operations
amurzina/made-cpp-2020-hw pull request #3
Opened 2020-10-06 18:44 UTC by amurzina

2020-10-17 23:17 UTC, xterrafunny requested changes

2020-10-17 23:17 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+(const std::vector<double> &first, const std::vector<double> &second) {
Отступы в 2 пробела

2020-10-17 23:17 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        std::vector<double> result;
Размер уже известен, зачем заставлять массив расширяться?

2020-10-17 23:17 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        }
Не работает для нулевых векторов

2020-10-17 23:17 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        return (first * second > 0) && (first || second);  // have collinearity and one direction
Не работает для нулевых векторов

2020-10-26 15:47 UTC, amurzina commented on vector_operations/src/vector_ops.h
> +    std::vector<double> operator+(const std::vector<double> &first, const std::vector<double> &second) {
а в чем проблема? Это стандартное форматирование CLion

2020-10-26 15:47 UTC, amurzina commented on vector_operations/src/vector_ops.h
> +        return (first * second > 0) && (first || second);  // have collinearity and one direction
fixed

2020-10-26 15:48 UTC, amurzina commented on vector_operations/src/vector_ops.h
> +        }
fixed

2020-10-26 15:49 UTC, amurzina commented on vector_operations/src/vector_ops.h
> +        std::vector<double> result;
fixed

2020-10-29 02:18 UTC, merged